"""Finding things on a page that does not want to be automated.

This is the hard part of the whole project, and the original did it the way
that cannot work:

    divs = soup.find_all("div", class_="Bdrs(8px) Bgz(cv) Bgp(c) StretchedBox")
    btn = '/html/body/div[1]/div/div[1]/div/main/div[1]/div/div/div[1]/div[1]/'
          'div/div[4]/div/div[4]/button'

Those class names are generated by Atomic CSS, so they encode styling rather
than meaning and change whenever the design does. The XPath is a literal path
through the DOM, so inserting one wrapper div anywhere above the button breaks
it. Both already broke, which is why the README says the project is broken.

Neither can be made reliable. What can be made reliable is *failing usefully*:
try several strategies in a defined order, report which one worked, and say
specifically what could not be found when none do. A run that reports "the like
button moved" is fixable in minutes. A run that reports `NoSuchElementException`
with an absolute XPath is an afternoon.

Strategies are ordered most to least stable:

1. `data-testid` and ARIA roles. Set deliberately, and survive restyling.
2. Accessible name, which is tied to what the control means.
3. Structural CSS that describes a relationship rather than a style.
4. An absolute XPath. Last resort, and expected to rot.

A `Locator` carries all of them. `find` returns the first that matches and
which one it was, so drift is visible in the logs before it becomes a failure.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

#: Atomic CSS: a property abbreviation, then a value in brackets. "Bdrs(8px)",
#: "Bgz(cv)", "Mb(20px)". Matching these means matching the styling.
ATOMIC_CLASS = re.compile(r"^[A-Za-z]{1,6}\([^)]*\)$")


def is_atomic_class(name: str) -> bool:
    """Whether a class name is generated styling rather than meaning.

    Used to warn when a selector is built on one, because it will break and the
    warning is cheaper than the debugging.
    """
    return bool(ATOMIC_CLASS.match(name.strip()))


def atomic_classes(selector: str) -> list[str]:
    r"""Any atomic class names inside a selector string.

    Backslashes are stripped first. A CSS selector has to escape the brackets
    in an atomic class name, so `Bdrs(8px)` appears as `Bdrs\(8px\)`, and
    tokenising without removing them means the check never fires on the exact
    selectors it exists to catch.
    """
    found = []
    for token in re.split(r"[\s.#\[\]>,=\"']+", selector.replace("\\", "")):
        if token and is_atomic_class(token):
            found.append(token)
    return found


@dataclass(frozen=True)
class Strategy:
    """One way of finding an element."""

    #: "css", "xpath", or "text".
    how: str
    what: str
    #: Lower is tried first.
    stability: int = 50

    @property
    def fragile(self) -> bool:
        """Whether this selector is expected to rot."""
        return (
            self.how == "xpath" and self.what.startswith("/html")
        ) or bool(atomic_classes(self.what))

    def why_fragile(self) -> str:
        if self.how == "xpath" and self.what.startswith("/html"):
            return "absolute XPath: one extra wrapper element anywhere above breaks it"
        atomic = atomic_classes(self.what)
        if atomic:
            return (
                "built on generated styling class(es) "
                + ", ".join(atomic)
                + ": these change whenever the design does"
            )
        return ""


@dataclass
class Locator:
    """A named element, and every way known to find it."""

    name: str
    strategies: list[Strategy] = field(default_factory=list)

    def ordered(self) -> list[Strategy]:
        return sorted(self.strategies, key=lambda s: (s.stability, s.fragile))

    def find(self, driver: Any) -> tuple[Any, Strategy]:
        """The element, and which strategy found it.

        Raises `LocatorError` naming every strategy tried, rather than the
        exception from whichever happened to be last.
        """
        attempts = []
        for strategy in self.ordered():
            try:
                element = _find_one(driver, strategy)
            except Exception as exc:  # noqa: BLE001
                # Selenium raises a family of exceptions here and a stale
                # element can raise anything; all of them mean "not this one".
                attempts.append(f"{strategy.how}={strategy.what!r} ({type(exc).__name__})")
                continue
            if element is not None:
                return element, strategy
            attempts.append(f"{strategy.how}={strategy.what!r} (no match)")

        raise LocatorError(
            f"could not find {self.name!r}. Tried {len(attempts)} strategy(ies):\n"
            + "\n".join(f"  {a}" for a in attempts)
            + "\n\nThe page has almost certainly changed. Update the strategies "
            f"for {self.name!r} in swipeml/automation/locators.py."
        )

    def find_or_none(self, driver: Any) -> tuple[Any, Strategy] | None:
        try:
            return self.find(driver)
        except LocatorError:
            return None

    def fragility_report(self) -> list[str]:
        return [
            f"{self.name}: {s.how}={s.what!r} - {s.why_fragile()}"
            for s in self.ordered() if s.fragile
        ]


class LocatorError(RuntimeError):
    """Nothing matched, and the message says what was tried."""


#: The strategy types `_find_one` knows how to apply.
STRATEGY_TYPES = frozenset({"css", "xpath", "text"})


def _find_one(driver: Any, strategy: Strategy) -> Any:
    """Apply one strategy. Separated so it can be stubbed in tests."""
    # Validated before Selenium is imported. A typo in a strategy type is this
    # module's bug and should say so, rather than reporting a missing optional
    # dependency and sending someone off to install Selenium.
    if strategy.how not in STRATEGY_TYPES:
        raise ValueError(
            f"unknown strategy {strategy.how!r}; use one of "
            + ", ".join(sorted(STRATEGY_TYPES))
        )

    from selenium.webdriver.common.by import By

    if strategy.how == "css":
        found = driver.find_elements(By.CSS_SELECTOR, strategy.what)
    elif strategy.how == "xpath":
        found = driver.find_elements(By.XPATH, strategy.what)
    elif strategy.how == "text":
        # An accessible name, matched case-insensitively on the button text.
        found = driver.find_elements(
            By.XPATH,
            "//button[contains(translate(normalize-space(.), "
            f"'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), "
            f"'{strategy.what.lower()}')]",
        )
    else:  # pragma: no cover - STRATEGY_TYPES is checked above
        raise ValueError(f"unknown strategy {strategy.how!r}")

    for element in found:
        try:
            if element.is_displayed():
                return element
        except Exception:  # noqa: BLE001 - a stale element is simply not it
            continue
    return None


# -- the locators ----------------------------------------------------------
#
# These are the current best guesses. They are expected to need updating, which
# is the point of having several per element and of reporting which one worked.

LIKE_BUTTON = Locator("like button", [
    Strategy("css", 'button[aria-label*="Like" i]', stability=10),
    Strategy("css", '[data-testid="gamepadLike"]', stability=15),
    Strategy("text", "like", stability=30),
    Strategy("css", 'main button:has(svg[viewBox])', stability=60),
])

PASS_BUTTON = Locator("pass button", [
    Strategy("css", 'button[aria-label*="Nope" i]', stability=10),
    Strategy("css", 'button[aria-label*="Pass" i]', stability=12),
    Strategy("css", '[data-testid="gamepadNope"]', stability=15),
    Strategy("text", "nope", stability=30),
])

PROFILE_CARD = Locator("profile card", [
    Strategy("css", '[data-testid="card"]', stability=10),
    Strategy("css", 'main div[role="button"][aria-label]', stability=25),
    Strategy("css", "div.StretchedBox", stability=70),
])

#: The one the original depended on entirely, kept last and marked for what it
#: is. Matching generated styling classes is why this stopped working.
CARD_IMAGE = Locator("card image", [
    Strategy("css", '[data-testid="card"] div[style*="background-image"]', stability=10),
    Strategy("css", 'div[aria-label][style*="background-image"]', stability=20),
    Strategy("css", 'div[style*="background-image"]', stability=40),
    Strategy("css", "div.Bdrs\\(8px\\).Bgz\\(cv\\)", stability=90),
])

ALL_LOCATORS = (LIKE_BUTTON, PASS_BUTTON, PROFILE_CARD, CARD_IMAGE)

#: A CSS url(...) value. The quoted forms are tried first and matched to their
#: closing quote, so a ')' inside a quoted URL is not treated as the end of the
#: value. Query strings carrying signatures and tokens do contain brackets.
BACKGROUND_URL = re.compile(
    r"""url\(\s*(?:"(?P<double>[^"]*)"|'(?P<single>[^']*)'|(?P<bare>[^)]*))\s*\)""",
)


def extract_background_url(style: str) -> str | None:
    """The URL out of a `background-image` style.

    The original did `.replace('url(', '').replace(')', '')`, which leaves the
    surrounding quotes attached when the value is quoted, and quotes in a URL
    passed to `requests.get` produce a 404 rather than an error anyone can read.
    """
    if not style:
        return None
    found = BACKGROUND_URL.search(style)
    if not found:
        return None
    url = (found.group("double") or found.group("single")
           or found.group("bare") or "").strip()
    return url or None


def fragility_report() -> str:
    """Every selector expected to rot, and why.

    Worth printing before a long run: it is a list of what will break and in
    which order the fallbacks will take over.
    """
    lines = []
    for locator in ALL_LOCATORS:
        lines += locator.fragility_report()
    if not lines:
        return "no fragile selectors"
    heading = f"{len(lines)} fragile selector(s):"
    return "\n".join([heading] + [f"  {line}" for line in lines])
